[package]
name = "basecracker"
version = "0.1.0"
authors = ["skyf0l"]
edition = "2018"
description = "A base cracker tool for ctfs and guessings"
repository = "https://github.com/skyf0l/BaseCracker"
readme = "README.md"
keywords = ["cracker", "base64", "hex", "ctf"]
categories = ["ctf-tools"]
# license = ""

[dependencies]

[dependencies.rug]
version = "1.14"
default-features = false
features = ["integer"]
