[package]
name = "basecracker"
version = "0.1.0"
authors = ["skyf0l"]
edition = "2018"
description = "A base cracker tool for ctfs and guessings"
repository = "https://github.com/skyf0l/BaseCracker"
readme = "README.md"
keywords = ["cracker", "base64", "hex", "ctf"]
categories = ["ctf-tools"]
# license = ""

[dependencies]
serde_json = "1.0.59"

[dependencies.rug]
version = "1.14"
default-features = false
features = ["integer"]

[dependencies.clap]
version = "3.1.6"
features = ["derive"]
