name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  RUST_BACKTRACE: 1

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - stable
          - beta
          - nightly
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}
          override: true
          components: rustfmt

      - name: clean
        run: cargo clean

      - name: build
        run: cargo build

      - name: test
        run: cargo test

      - name: ignored test
        run: cargo test -- --ignored || true
        if: matrix.version == 'nightly'

      - name: check formatting
        run: cargo fmt -- --check

  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        version:
          - nightly
        target:
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}
          override: true

      - name: build
        run: cargo build

      - name: test
        run: cargo test -- || true

  mac:
    name: MacOs
    runs-on: macos-latest
    strategy:
      matrix:
        version:
          - nightly
        target:
          - x86_64-apple-darwin
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}
          override: true

      - name: build
        run: cargo build

      - name: test
        run: cargo test -- || true
