name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  RUST_BACKTRACE: 1

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: |-
    ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - name: Stable with rustfmt and clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-tarpaulin

      - name: Check coding style
        run: cargo fmt --check --all

      - name: Lint
        run: cargo clippy --all-targets -- -D warnings

      - name: Build
        run: cargo build

      - name: Test
        run: cargo tarpaulin --out Xml

      - name: Upload to codecov.io
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov

  windows:
    name: Build on Windows
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest

      - name: Build
        run: cargo build

      - name: Test
        run: cargo nextest run

  mac:
    name: Build on MacOs
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest

      - name: Build
        run: cargo build

      - name: Test
        run: cargo nextest run
