name: Tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        shell: bash
        run: |
          cargo build --release

      - name: Run tests
        run: |
          cargo test --release
